### ISSUE TITLE
missing AnimationParticle example?

### ISSUE THREAD

**Issue by SeminYun** [CloudKidStudio/PixiParticlesEditor#5]
hi.

I finded  'AnimationParticle' part in lib.

but i couldn't find any example or something..

do you help for this?

thx a lot..

**Comment by andrewstart** [comment]
That is something I started, but don't consider finished yet - I need to find a better way of supplying it with the Array of Textures so that it can animate. I also don't know if Pixi v3 changed MovieClip in a way so that AnimatedParticle no longer works with it.

**Comment by SeminYun** [comment]
I see 

i hope you, meet again with better 

thx a lot.

**Comment by andrewstart** [comment]
[Release 1.5.0 of PixiParticles](https://github.com/CloudKidStudio/PixiParticles/releases/tag/1.5.0) has changed how AnimatedParticles work, and has also added examples for them in the library (not the tool).
