### ISSUE TITLE
performance is down in recycle 

### ISSUE THREAD

**Issue by SeminYun** [CloudKidStudio/PixiParticlesEditor#7]
hi.

client is slow when 10000 or more  particles emiited.

it is becuase of recycle when profile

recycle in particle object will be busy,  90% or more.

is there possible to optimize ?

thx a lot always

**Comment by andrewstart** [comment]
[Release 1.5.0 of PixiParticles](https://github.com/CloudKidStudio/PixiParticles/releases/tag/1.5.0) has greatly improved performance, particularly in recycle().
